version: 2.1

commands:
  install_dependencies:
    description: "Install development dependencies."
    steps:
      - run: composer install
      - run: npm ci
  mkdir_artifacts:
    description: "Make Artifacts directory"
    steps:
      - run:
          command: |
            [ ! -d "/tmp/artifacts" ] && mkdir /tmp/artifacts &>/dev/null

executors:
  base:
    docker:
      - image: circleci/buildpack-deps:latest
    working_directory: /tmp
  php_node:
    docker:
      - image: circleci/php:7.3.3-stretch-node-browsers
    working_directory: /tmp/theme
  python:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: /tmp

jobs:
  checkout:
    executor: base
    steps:
      - checkout:
          path: theme
      - persist_to_workspace:
          root: /tmp
          paths:
            - theme

  standards:
    executor: php_node
    steps:
      - attach_workspace:
          at: /tmp
      - install_dependencies
      - run: composer phpcs
      - run: npm run lint:css
      - run: npm run lint:js

  bundle:
    executor: php_node
    steps:
      - attach_workspace:
          at: /tmp
      - run: npm ci
      - run: npm run zip
      - mkdir_artifacts
      - run: mv ./*.zip /tmp/artifacts/.
      - persist_to_workspace:
          root: /tmp
          paths:
            - artifacts
            - theme
      - store_artifacts:
          path: /tmp/artifacts/

  create_data_file:
    executor: php_node
    steps:
      - attach_workspace:
          at: /tmp
      - run: npm run prep:piservice /tmp/artifacts
      - persist_to_workspace:
          root: /tmp
          paths:
            - artifacts

  deploy_staging:
    executor: python
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: "Set S3_PATH env variable"
          command: |
            echo "export S3_PATH=$(grep 'textdomain' /tmp/theme/package.json | awk -F: '{print $2}' | sed 's/^\s//' | sed 's/\"//g')" >> ${BASH_ENV}
      - aws-s3/sync:
          from: "/tmp/artifacts/"
          to: "s3://update.atomicblocks.com/themes/${S3_PATH}/"

  deploy_s3:
    executor: python
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: "Set S3_PATH env variable"
          command: |
            echo "export S3_PATH=$(grep 'textdomain' /tmp/theme/package.json | awk -F: '{print $2}' | sed 's/^\s//' | sed 's/\"//g')" >> ${BASH_ENV}
      - aws-s3/sync:
          from: "/tmp/artifacts/"
          to: "s3://update.atomicblocks.com/themes/${S3_PATH}/"

workflows:
  version: 2
  lint:
    jobs:
      - checkout
      - standards

  deploy:
    jobs:
      - checkout:
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
                - staging
      - standards:
          requires:
            - checkout
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
                - staging
      - bundle:
          requires:
            - standards
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
                - staging
      - create_data_file:
          requires:
            - bundle
          filters:
            tags:
              only: /.*/
            branches:
              only:
                - master
                - staging
      - deploy_staging:
          context: wpe-product-info-aws
          requires:
            - create_data_file
          filters:
            tags:
              only: /.*/
            branches:
              only: staging
      - deploy_s3:
          context: wpe-product-info-aws
          requires:
            - create_data_file
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              only: master

orbs:
  aws-s3: circleci/aws-s3@1.0.0
